slackhq/slack-lints

.github/workflows/ci.yml
build.gradle.kts
slack-lint/src/main/java/slack/lint/MoshiUsageDetector.kt
slack-lint/src/main/java/slack/lint/inclusive/InclusiveNamingSourceCodeScanner.kt

This updates a few deps and also sets up CI to test compilation against newer versions. Unfortunately we can't also test newer versions on CI because test outputs change slightly between different versions.

Support newer lint versions

---

slack-lint-annotations/src/main/kotlin/slack/lint/annotations/RestrictCallsTo.kt
slack-lint/src/main/java/slack/lint/RestrictCallsToDetector.kt
slack-lint/src/main/java/slack/lint/SlackIssueRegistry.kt
slack-lint/src/test/java/slack/lint/RestrictCallsToDetectorTest.kt

This implements a new detector for a new `@RestrictCallsTo` annotation. This is similar to `@RestrictTo`, but is specifically just targeted at `UCallExpression`s. This is useful for APIs that can be safely implemented but are not expected to be _called_ externally, such as overrides for lifecycle callbacks.

Implement `@RestrictCallsTo` lint

---

slack-lint/src/main/java/slack/lint/DeprecatedAnnotationDetector.kt
slack-lint/src/test/java/slack/lint/DeprecatedAnnotationDetectorTest.kt

In order to better analyze our deprecated calls in lint reports, it would be helpful if reports identified the referenced deprecation. This PR prefixes the error message with the referenced deprecation when it is available.

Call out the deprecated call in the lint message when reporting

---

.github/workflows/ci.yml
gradle/libs.versions.toml
slack-lint/lint-baseline.xml
slack-lint/src/main/java/slack/lint/SlackIssueRegistry.kt
slack-lint/src/main/java/slack/lint/util/LintUtils.kt
slack-lint/src/test/java/slack/lint/MoshiUsageDetectorTest.kt

This updates our project to the latest lint APIs and also begins targeting building against latest. This should fix compatibility on newer studio versions + ease updates in the future by targeting latest (even while we still support lower versions).

Update lint versions and target latest

---

slack-lint/src/main/java/slack/lint/SlackIssueRegistry.kt
slack-lint/src/main/java/slack/lint/eithernet/DoNotExposeEitherNetInRepositoriesDetector.kt
slack-lint/src/test/java/slack/lint/eithernet/DoNotExposeEitherNetInRepositoriesDetectorTest.kt

We don't want folks to expose these types directly in the repository layer, it creates awkward situations where the UI suddenly has to know what to do about network failures as a state.

Implement DoNotExposeEitherNetInRepositoriesDetector

---

slack-lint/src/main/java/slack/lint/eithernet/DoNotExposeEitherNetInRepositoriesDetector.kt
slack-lint/src/main/java/slack/lint/retrofit/RetrofitUsageDetector.kt
slack-lint/src/main/java/slack/lint/util/LintUtils.kt
slack-lint/src/test/java/slack/lint/eithernet/DoNotExposeEitherNetInRepositoriesDetectorTest.kt
slack-lint/src/test/java/slack/lint/retrofit/RetrofitUsageDetectorTest.kt

These have to be handled in a special way in order to correctly read their return types

Fix support for suspend functions in EitherNet and Retrofit lints

---

gradle/libs.versions.toml
slack-lint/src/main/java/slack/lint/inclusive/InclusiveNamingChecker.kt
slack-lint/src/test/java/slack/lint/inclusive/InclusiveNamingDetectorTest.kt

I found a vague reference in the sample lint config on [this doc page](http://googlesamples.github.io/android-custom-lint-rules/usage/lintxml.md.html#configuringusinglint.xmlfiles/xmlsyntax) that took me down a path to finding there's a new options API in lint for configuring lint detectors via the standard lint xml config.
This updates the inclusive naming linter to use that pattern, so now we would add this entry to our `lint.xml` to configure this instead. Much nicer 👍.
```xml
<?xml version="1.0" encoding="UTF-8"?>
<lint>
<issue id="InclusiveNaming">
<option name="block-list" value="fork,knife,spoon,spork"/>
</issue>
</lint>
```

Use StringOption for inclusive naming lint

---

slack-lint/src/main/java/slack/lint/SlackIssueRegistry.kt
slack-lint/src/main/java/slack/lint/resources/FullyQualifiedResourceDetector.kt
slack-lint/src/main/java/slack/lint/resources/ImportAliasesLoader.kt
slack-lint/src/main/java/slack/lint/resources/MissingResourceImportAliasDetector.kt
slack-lint/src/main/java/slack/lint/resources/WrongResourceImportAliasDetector.kt
slack-lint/src/main/java/slack/lint/resources/model/RootIssueData.kt
slack-lint/src/test/java/slack/lint/resources/FullyQualifiedResourceDetectorTest.kt
slack-lint/src/test/java/slack/lint/resources/MissingResourceImportAliasDetectorTest.kt
slack-lint/src/test/java/slack/lint/resources/WrongResourceImportAliasDetectorTest.kt

This adds 3 lint checks that enforce the rules around referencing resources in a non-transitive R class world:
- [MissingResourceImportAliasDetector](https://github.com/slackhq/slack-lints/commit/c94bb42e8bfb3c7fc42581da9d9fca78c2077308) : enforces that only the local module's R class can be imported without an import alias.
- [WrongResourceImportAliasDetector](https://github.com/slackhq/slack-lints/commit/90a0d2dc20ff21268d3676e3f0ff2723a9269f0b): enforces that the import aliases for R classes are consistent across the codebase.
- [FullyQualifiedResourceDetector](https://github.com/slackhq/slack-lints/commit/17dbcc04c02ee3ade8872964ba01f82f213c82f6): enforces that R classes aren't referenced using their fully qualified names.
Best reviewed by commit.
| MissingResourceImportAliasDetector …

Add non-transitive R class lints

---

slack-lint/src/main/java/slack/lint/resources/FullyQualifiedResourceDetector.kt
slack-lint/src/main/java/slack/lint/resources/MissingResourceImportAliasDetector.kt
slack-lint/src/test/java/slack/lint/resources/FullyQualifiedResourceDetectorTest.kt
slack-lint/src/test/java/slack/lint/resources/MissingResourceImportAliasDetectorTest.kt

This updates `MissingResourceImportAliasDetector` to use the module's package name instead of the file's to avoid false positives for modules with custom namespaces. It also updates the fix name for `FullyQualifiedResourceDetector`.

Fix non-transitive R class lints

---

slack-lint-checks/lint-baseline.xml
slack-lint-checks/src/main/java/slack/lint/SlackIssueRegistry.kt
slack-lint-checks/src/main/java/slack/lint/compose/ComposeCompositionLocalNamingDetector.kt
slack-lint-checks/src/main/java/slack/lint/compose/ComposeCompositionLocalUsageDetector.kt
slack-lint-checks/src/main/java/slack/lint/compose/ComposeContentEmitterReturningValuesDetector.kt
slack-lint-checks/src/main/java/slack/lint/compose/ComposeModifierMissingDetector.kt
slack-lint-checks/src/main/java/slack/lint/compose/ComposeModifierReusedDetector.kt
slack-lint-checks/src/main/java/slack/lint/compose/ComposeModifierWithoutDefaultDetector.kt
slack-lint-checks/src/main/java/slack/lint/compose/ComposeMultipleContentEmittersDetector.kt
slack-lint-checks/src/main/java/slack/lint/compose/ComposeMutableParametersDetector.kt
slack-lint-checks/src/main/java/slack/lint/compose/ComposeNamingDetector.kt
slack-lint-checks/src/main/java/slack/lint/compose/ComposeParameterOrderDetector.kt
slack-lint-checks/src/main/java/slack/lint/compose/ComposePreviewNamingDetector.kt
slack-lint-checks/src/main/java/slack/lint/compose/ComposePreviewPublicDetector.kt
slack-lint-checks/src/main/java/slack/lint/compose/ComposeRememberMissingDetector.kt
slack-lint-checks/src/main/java/slack/lint/compose/ComposeUnstableCollectionsDetector.kt
slack-lint-checks/src/test/java/slack/lint/compose/ComposeCompositionLocalNamingDetectorTest.kt
slack-lint-checks/src/test/java/slack/lint/compose/ComposeCompositionLocalUsageDetectorTest.kt
slack-lint-checks/src/test/java/slack/lint/compose/ComposeContentEmitterReturningValuesDetectorTest.kt
slack-lint-checks/src/test/java/slack/lint/compose/ComposeModifierMissingDetectorTest.kt
slack-lint-checks/src/test/java/slack/lint/compose/ComposeModifierReusedDetectorTest.kt
slack-lint-checks/src/test/java/slack/lint/compose/ComposeModifierWithoutDefaultDetectorTest.kt
slack-lint-checks/src/test/java/slack/lint/compose/ComposeMultipleContentEmittersDetectorTest.kt
slack-lint-checks/src/test/java/slack/lint/compose/ComposeMutableParametersDetectorTest.kt
slack-lint-checks/src/test/java/slack/lint/compose/ComposeNamingDetectorTest.kt
slack-lint-checks/src/test/java/slack/lint/compose/ComposeParameterOrderDetectorTest.kt
slack-lint-checks/src/test/java/slack/lint/compose/ComposePreviewNamingDetectorTest.kt
slack-lint-checks/src/test/java/slack/lint/compose/ComposePreviewPublicDetectorTest.kt
slack-lint-checks/src/test/java/slack/lint/compose/ComposeRememberMissingDetectorTest.kt
slack-lint-checks/src/test/java/slack/lint/compose/ComposeUnstableCollectionsDetectorTest.kt

Figured out a few things
- I had the trailing `\` characters backward. That's only if you want to continue on a newline in source but not actually in the real message. So I've removed them here as we _do_ want the newlines where they are.
- Figured out the trimIndent() stuff. It's not necessary when passing a string into the explanation field of an `Issue` creation, but _is_ still necessary for messages passed into a `context.report(...)` call.
- Removed extra newlines in explanations (see comments below w/ screenshots for why).

Fix compose lint explanation strings

---

gradle/libs.versions.toml
slack-lint-checks/build.gradle.kts
slack-lint-checks/src/main/java/slack/lint/mocking/AbstractMockDetector.kt
slack-lint-checks/src/main/java/slack/lint/mocking/DataClassMockDetector.kt
slack-lint-checks/src/main/java/slack/lint/mocking/DoNotMockMockDetector.kt
slack-lint-checks/src/main/java/slack/lint/util/LintUtils.kt
slack-lint-checks/src/main/java/slack/lint/util/SlackJavaEvaluator.kt

Resolves #53
This implements a new decorating `SlackJavaEvaluator` that leverages Kotlin `Metadata` to understand kotlin langauge features of externally compiled elements. This is important as these elements otherwise appear to lint as just plain Java classes. I've done a bunch of testing with this in the Slack Android repo, and the timings are always ~1ms, rarely exceeding it to 2ms. Just in case though, I've gated this behavior with a system property.
Currently this is only used in the DoNotMock checkers, but is usable in other future checkers.

Use kotlinx-metadata for more accurate Kotlin checks

---

slack-lint-checks/src/test/java/slack/lint/mocking/SealedClassMockDetectorTest.kt

New lint API unlocked this after https://issuetracker.google.com/issues/283693337 was fixed

Update java sealed test checks

---

slack-lint-checks/src/main/java/slack/lint/denylistedapis/DenyListedApiDetector.kt
slack-lint-checks/src/test/java/slack/lint/denylistedapis/DenyListedApiDetectorTest.kt

Adding `runCatching` to the deny list as it behaves the same as a try/catch catching any throwable, potentially catching unintended exceptions. Which when used with coroutines it catches and doesn't rethrow CancellationExceptions.

Add runCatching to the denylist

---

slack-lint-checks/src/main/java/slack/lint/denylistedapis/DenyListedApiDetector.kt
slack-lint-checks/src/test/java/slack/lint/denylistedapis/DenyListedApiDetectorTest.kt

This also opportunistically improves our error message reporting here to only report the name of the function in the call and be more precise, as linting the entire function cal adds a lot of noise in long chained calls

Add blocking rxjava and coroutines calls to denylist

---

slack-lint-checks/src/main/java/slack/lint/mocking/MockDetector.kt
slack-lint-checks/src/test/java/slack/lint/mocking/MockReportTest.kt

This adds a new on-demand feature to write a report file of incorrectly mocked types. The idea with this is that we can write a tool that scrapes this output file separately after a lint run and aggregate the most commonly mocked types, and use that as a heuristic of what should be prioritized in writing fakes.

Add mock report option to MockDetector

---

slack-lint-checks/src/main/java/slack/lint/mocking/MockDetector.kt
slack-lint-checks/src/test/java/slack/lint/mocking/MockReportTest.kt

This allows us to optionally include _all_ mocked types found in mock report files, not just errors. We'd never report non-errors as lint errors, but this gives us some useful infrastructure to reuse. Especially important as not all mock type checkers are error severity.

Add support for mock report modes + CSV format

---

slack-lint-checks/src/main/java/slack/lint/util/LintUtils.kt

This adds an extra layer to the swiss cheese to try to capture these types. Since kotlin 1.5, kotlinc will generate this annotation onto JVM value classes.
Note we don't enable this check in our registry yet due to #88

Add an extra annotation-based check for value classes

---

slack-lint-checks/src/main/java/slack/lint/mocking/SealedClassMockDetector.kt

Emphasizing it's not possible in java 17+

Improve the sealed class mock detector

---

slack-lint-checks/src/test/java/slack/lint/LintKotlinVersionCheckTest.kt

Lint chases kotlin versions surprisingly quick, including RCs. This adds a test so we can keep track of this and not be surprised. For example, starting in 31.3.0-alpha06 they moved to kotlin 1.9.20 betas

Add LintKotlinVersionCheckTest

---

build.gradle.kts
gradle/libs.versions.toml
slack-lint-checks/build.gradle.kts
slack-lint-checks/src/test/java/slack/lint/LintKotlinVersionCheckTest.kt

This is some upkeep work to update our lint kotlin target and simplify the future maintenance of it by aligning the lint version used everywhere

Update kotlin language version to match latest in lint + clean up

---

slack-lint-checks/build.gradle.kts
slack-lint-checks/lint-baseline.xml

UastImplementation catches uses of underlying uast impls, + enables a few other useful lint-specific errors to fatal

Add new lint configs + update baseline

---

slack-lint-checks/src/main/java/slack/lint/SlackIssueRegistry.kt
slack-lint-checks/src/main/java/slack/lint/mocking/AnyMockDetector.kt
slack-lint-checks/src/main/java/slack/lint/mocking/MockDetector.kt

This allows flagging _any_ mock as an error. Off by default.

Add AnyMockDetector

---

slack-lint-checks/src/main/java/slack/lint/mocking/MockDetector.kt

I spend quite some time figuring out why configuring the various "Do Not Mock" lint checks were not working with [Mockito Kotlin](https://github.com/mockito/mockito-kotlin), even after configuring the `mock-factories` through `lint.xml`. I configured it like this:
```xml
<issue id="DoNotMock">
<option name="mock-factories" value="org.mockito.kotlin.MockingKt#mock,org.mockito.kotlin.SpyingKt#spy" />
</issue>
<issue id="DoNotMockDataClass">
<option name="mock-factories" value="org.mockito.kotlin.MockingKt#mock,org.mockito.kotlin.SpyingKt#spy" />
</issue>
<issue id="DoNotMockObjectClass">
<option name="mock-factories" value="org.mockito.kotlin.MockingKt#mock,org.mockito.kotlin.SpyingKt#spy" />
</issue>
```
However, it did not work until I added the option for `DoNotMockRecordClass`
```xml …
```

Expand Mock option explanation for use with multiple issues.

---

gradle/libs.versions.toml
slack-lint-checks/build.gradle.kts
slack-lint-checks/src/main/java/slack/lint/util/MetadataJavaEvaluator.kt
slack-lint-checks/src/main/java/slack/lint/util/Names.kt

kotlin-metadata is now stable in K2, but we still have to shade it for a couple reasons
- lint still targets kotlin 1.9
- lint also only includes the stdlib on the classpath, not metadata
Also updates the shadow plugin to its new coordinates: https://github.com/GradleUp/shadow/releases/tag/8.3.0

Switch to stable kotlin metadata + update shadow plugin

---

slack-lint-checks/src/main/java/slack/lint/denylistedapis/DenyListedApiDetector.kt
slack-lint-checks/src/test/java/slack/lint/denylistedapis/DenyListedApiDetectorTest.kt

Update rx-coroutines interop lint message to:
> rxSingle defaults to Dispatchers.Default. Provide an explicit dispatcher which can be replaced with a test dispatcher to make your tests more deterministic.
As `Dispatchers.Unconfined` may lead to unintended threading and should only be used deliberately, remove it as a recommendation from the lint message.

Update rx-coroutines interop lint message

---

CHANGELOG.md
slack-lint-checks/src/main/java/slack/lint/NotNullOperatorDetector.kt
slack-lint-checks/src/main/java/slack/lint/SlackIssueRegistry.kt
slack-lint-checks/src/main/java/slack/lint/ui/DoNotCallViewToString.kt
slack-lint-checks/src/main/java/slack/lint/ui/ItemDecorationViewBindingDetector.kt
slack-lint-checks/src/test/java/slack/lint/NotNullOperatorDetectorTest.kt

Open-sources `AvoidUsingNotNullOperator`, `InflationInItemDecoration`, and `DoNotCallViewToString` checks.

Open-source new checks

---

slack-lint-checks/src/main/java/slack/lint/retrofit/RetrofitUsageDetector.kt
slack-lint-checks/src/test/java/slack/lint/retrofit/RetrofitUsageDetectorTest.kt

This PR updates the `RetrofitUsageDetector` to include support for `@Multipart` annotated methods and `@Part` annotated parameters per [Retrofit doc](https://square.github.io/retrofit/#:~:text=FORM%20ENCODED%20AND%20MULTIPART). Added test cases for new lints and success path.
* [x ] I've read and understood the [Contributing Guidelines](https://github.com/{project_slug}/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [ x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x ] I've written tests to cover the new code and functionality included in this PR.
> The following point can be removed after …

Add @Multipart/@Part Retrofit lint updates

---

slack-lint-checks/src/main/java/slack/lint/ExceptionMessageDetector.kt

Tests are not prod-facing and here they can be helpful for their contracts

Don't require ExceptionMessage lint in tests

---

slack-lint-checks/src/main/java/slack/lint/mocking/MockDetector.kt

This PR adds mockito-kotlin support to mocking factories, properly identifying when a consumer uses the `org.mockito.kotlin.mock` function to mock things like data classes. 
- https://github.com/slackhq/slack-lints/issues/356

Added mockito-kotlin mock/spy functions to mock factories

---

slack-lint-checks/src/main/java/slack/lint/rx/RxObservableEmitDetector.kt

This PR fixes a bug where lint builds would fail due to the following error:
`Message: You must override visitCallExpression (and don't call super.visitCallExpression!)`
Resolves #400

Return false instead of calling super in RxObservableEmitDetector

---

slack-lint-checks/src/main/java/slack/lint/SlackIssueRegistry.kt

We've narrowed down the cause of #400 to `AlwaysNullReadOnlyVariableDetector`. We're not entirely sure why this detector is causing the error, but we're going to disable it temporarily to allow the other detectors to be updated as we investigate it further.
Fixes #400

Remove AlwaysNullReadOnlyVariableDetector from SlackIssueRegistry

---

slack-lint-checks/src/main/java/slack/lint/JsonInflaterMoshiCompatibilityDetector.kt
slack-lint-checks/src/test/java/slack/lint/JsonInflaterMoshiCompatibilityDetectorTest.kt

This PR updates `JsonInflaterMoshiCompatibilityDetector` to accept sealed interfaces as Moshi-compatible if they're annotated with `JsonClass` or `AdaptedBy`.

Allow sealed interfaces to be Moshi-compatible

---

slack-lint-checks/src/main/java/slack/lint/JsonInflaterMoshiCompatibilityDetector.kt
slack-lint-checks/src/test/java/slack/lint/JsonInflaterMoshiCompatibilityDetectorTest.kt

This PR updates `JsonInflaterMoshiCompatibilityDetector` to accept primitives in parameterized types as Moshi-compatible.

Allow primitives in collections to be Moshi-compatible
